<?php
namespace FatSolicitacoes;

require "../header/header.php";

require "../services/conexao.php";

use Banco\Conexao;

class FatSolicitacoes
{
    public function getArray($query)
    {
        while($registro = sqlsrv_fetch_array($query)){
            $array[] = [
                'FAT_EMPRESA'  => $registro['FAT_EMPRESA'],
                'FAT_LOCAL'  => $registro['FAT_LOCAL'],
                'SIM_ORIGEM'  => $registro['SIM_ORIGEM'],
                'FAT_SOLICITACAO'  => $registro['FAT_SOLICITACAO'],
                'FAT_SOLICITACAO_SEQUENCIA'  => $registro['FAT_SOLICITACAO_SEQUENCIA'],
                'SIM_LOCAL_DESTINO'  => $registro['SIM_LOCAL_DESTINO'],
                'PCV_ENTIDADE'  => $registro['PCV_ENTIDADE'],
                'PCV_ENTIDADE_FATURAMENTO'  => $registro['PCV_ENTIDADE_FATURAMENTO'],
                'SIM_ENDERECO_FATURAMENTO'  => $registro['SIM_ENDERECO_FATURAMENTO'],
                'SIM_ENDERECO_ENTREGA'  => $registro['SIM_ENDERECO_ENTREGA'],
                'SIM_ENDERECO_COBRANCA'  => $registro['SIM_ENDERECO_COBRANCA'],
                'SIM_OPERACAO'  => $registro['SIM_OPERACAO'],
                'SIM_VIA_TRANSPORTE'  => $registro['SIM_VIA_TRANSPORTE'],
                'SIM_DOCUMENTO_ID'  => $registro['SIM_DOCUMENTO_ID'],
                'PCV_PLANO_PAGAMENTO'  => $registro['PCV_PLANO_PAGAMENTO'],
                'PCV_TIPO_TAB_PRECO'  => $registro['PCV_TIPO_TAB_PRECO'],
                'PCV_TRANSPORTADORA'  => $registro['PCV_TRANSPORTADORA'],
                'CGF_CENTRO_CUSTO'  => $registro['CGF_CENTRO_CUSTO'],
                'FAT_TIPO_SOLICITACAO'  => $registro['FAT_TIPO_SOLICITACAO'],
                'TIPO_NOTA_FISCAL'  => $registro['TIPO_NOTA_FISCAL'],
                'TIPO_FRETE'  => $registro['TIPO_FRETE'],
                'STATUS'  => $registro['STATUS'],
                'PEDIDO_ORIGINAL'  => $registro['PEDIDO_ORIGINAL'],
                'PEDIDO_SEQ_ORIGINAL'  => $registro['PEDIDO_SEQ_ORIGINAL'],
                'NF_ORIGINAL'  => $registro['NF_ORIGINAL'],
                'DATA_EMISSAO_NF_ORIGINAL'  => $registro['DATA_EMISSAO_NF_ORIGINAL'],
                'DATA_SOLICITACAO'  => $registro['DATA_SOLICITACAO'],
                'DATA_PROVAVEL_FATURAMENTO'  => $registro['DATA_PROVAVEL_FATURAMENTO'],
                'DATA_PRECO'  => $registro['DATA_PRECO'],
                'SEU_PEDIDO'  => $registro['SEU_PEDIDO'],
                'COMPROMISSO'  => $registro['COMPROMISSO'],
                'NF_DIGITADA'  => $registro['NF_DIGITADA'],
                'EMITE_NF'  => $registro['EMITE_NF'],
                'PERC_FRETE'  => $registro['PERC_FRETE'],
                'PERC_SEGURO'  => $registro['PERC_SEGURO'],
                'PERC_DESCONTO'  => $registro['PERC_DESCONTO'],
                'PERC_DESCONTO_FINANCEIRO'  => $registro['PERC_DESCONTO_FINANCEIRO'],
                'PERC_ENCARGOS_FINANCEIROS'  => $registro['PERC_ENCARGOS_FINANCEIROS'],
                'DIAS_DESCONTO_FINANCEIRO'  => $registro['DIAS_DESCONTO_FINANCEIRO'],
                'VALOR_ANTECIPADO'  => $registro['VALOR_ANTECIPADO'],
                'VALOR_FRETE'  => $registro['VALOR_FRETE'],
                'VALOR_SEGURO'  => $registro['VALOR_SEGURO'],
                'VALOR_OUT_DESPESAS'  => $registro['VALOR_OUT_DESPESAS'],
                'VALOR_DESCONTO'  => $registro['VALOR_DESCONTO'],
                'VALOR_ENCARGOS_FINANCEIROS'  => $registro['VALOR_ENCARGOS_FINANCEIROS'],
                'PESO_LIQUIDO'  => $registro['PESO_LIQUIDO'],
                'PESO_BRUTO'  => $registro['PESO_BRUTO'],
                'CFO_ITENS'  => $registro['CFO_ITENS'],
                'OBSERVACAO_FATURAMENTO_01'  => $registro['OBSERVACAO_FATURAMENTO_01'],
                'OBSERVACAO_FATURAMENTO_02'  => $registro['OBSERVACAO_FATURAMENTO_02'],
                'OBSERVACAO_FATURAMENTO_03'  => $registro['OBSERVACAO_FATURAMENTO_03'],
                'OBSERVACAO_NOTA_FISCAL_01'  => $registro['OBSERVACAO_NOTA_FISCAL_01'],
                'OBSERVACAO_NOTA_FISCAL_02'  => $registro['OBSERVACAO_NOTA_FISCAL_02'],
                'OBSERVACAO_NOTA_FISCAL_03'  => $registro['OBSERVACAO_NOTA_FISCAL_03'],
                'BASE_ICMS'  => $registro['BASE_ICMS'],
                'VALOR_ICMS'  => $registro['VALOR_ICMS'],
                'BASE_ICMS_SUBST_TRIBUTARIA'  => $registro['BASE_ICMS_SUBST_TRIBUTARIA'],
                'VALOR_ICMS_SUBST_TRIBUTARIA'  => $registro['VALOR_ICMS_SUBST_TRIBUTARIA'],
                'BASE_IPI'  => $registro['BASE_IPI'],
                'VALOR_IPI'  => $registro['VALOR_IPI'],
                'VALOR_ISS'  => $registro['VALOR_ISS'],
                'BASE_ISS'  => $registro['BASE_ISS'],
                'BASE_IRRF'  => $registro['BASE_IRRF'],
                'VALOR_IRRF'  => $registro['VALOR_IRRF'],
                'FCA_LINHA'  => $registro['FCA_LINHA'],
                'FAT_NOTA_FISCAL'  => $registro['FAT_NOTA_FISCAL'],
                'FAT_TALONARIO'  => $registro['FAT_TALONARIO'],
                'DATA_EMISSAO_NF'  => $registro['DATA_EMISSAO_NF'],
                'CLIENTE_EVENTUAL'  => $registro['CLIENTE_EVENTUAL'],
                'PERC_ICMS'  => $registro['PERC_ICMS'],
                'PERC_REDUCAO_ICMS'  => $registro['PERC_REDUCAO_ICMS'],
                'PERC_ICMS_FRETE'  => $registro['PERC_ICMS_FRETE'],
                'SIM_REPRESENTANTE'  => $registro['SIM_REPRESENTANTE'],
                'SAC_USUARIO_CADASTRO'  => $registro['SAC_USUARIO_CADASTRO'],
                'SAC_USUARIO_CORRECAO'  => $registro['SAC_USUARIO_CORRECAO'],
                'SAC_USUARIO_LIBERACAO'  => $registro['SAC_USUARIO_LIBERACAO'],
                'NF_DIGITADA_INCONSISTENTE'  => $registro['NF_DIGITADA_INCONSISTENTE'],
                'SIM_SEGMENTO'  => $registro['SIM_SEGMENTO'],
                'OBSERVACAO_NOTA_FISCAL_04'  => $registro['OBSERVACAO_NOTA_FISCAL_04'],
                'OBSERVACAO_NOTA_FISCAL_05'  => $registro['OBSERVACAO_NOTA_FISCAL_05'],
                'VALOR_IPI_DEVOLUCAO'  => $registro['VALOR_IPI_DEVOLUCAO'],
                'SIM_BANCO'  => $registro['SIM_BANCO'],
                'SIM_AGENCIA'  => $registro['SIM_AGENCIA'],
                'SIM_CONTA_CORRENTE'  => $registro['SIM_CONTA_CORRENTE'],
                'PCV_VEICULO'  => $registro['PCV_VEICULO'],
                'NOME_MOTORISTA'  => $registro['NOME_MOTORISTA'],
                'PCV_MOTORISTA'  => $registro['PCV_MOTORISTA'],
                'GERA_SERVICO'  => $registro['GERA_SERVICO'],
                'FAT_LOCAL_SERVICO'  => $registro['FAT_LOCAL_SERVICO'],
                'PERC_APROVEITAMENTO'  => $registro['PERC_APROVEITAMENTO'],
                'BLOQUEADO'  => $registro['BLOQUEADO'],
                'PERC_SERVICO_NF'  => $registro['PERC_SERVICO_NF'],
                'CAR_TIPO_COBRANCA'  => $registro['CAR_TIPO_COBRANCA'],
                'FRETE_VENDA'  => $registro['FRETE_VENDA'],
                'UF_VEICULO'  => $registro['UF_VEICULO'],
                'RG_MOTORISTA'  => $registro['RG_MOTORISTA'],
                'PCV_TIPO_CLIENTE'  => $registro['PCV_TIPO_CLIENTE'],
                'VALOR_JUROS'  => $registro['VALOR_JUROS'],
                'DATA_SAIDA'  => $registro['DATA_SAIDA'],
                'BASE_PIS_RETIDO'  => $registro['BASE_PIS_RETIDO'],
                'VALOR_PIS_RETIDO'  => $registro['VALOR_PIS_RETIDO'],
                'BASE_COFINS_RETIDO'  => $registro['BASE_COFINS_RETIDO'],
                'VALOR_COFINS_RETIDO'  => $registro['VALOR_COFINS_RETIDO'],
                'BASE_CSLL_RETIDO'  => $registro['BASE_CSLL_RETIDO'],
                'VALOR_CSLL_RETIDO'  => $registro['VALOR_CSLL_RETIDO'],
                'VENDA_VISTA_CHEQUE'  => $registro['VENDA_VISTA_CHEQUE'],
                'VALOR_ADIANTAMENTO'  => $registro['VALOR_ADIANTAMENTO'],
                'NOME_USUARIO'  => $registro['NOME_USUARIO'],
                'QTD_DIAS_PRORROGAR_NF'  => $registro['QTD_DIAS_PRORROGAR_NF'],
                'CMO_AGRUPAMENTO_ID'  => $registro['CMO_AGRUPAMENTO_ID'],
                'CREATED'  => $registro['CREATED'],
                'UPDATED'  => $registro['UPDATED'],
                'RETER_FUNRURAL'  => $registro['RETER_FUNRURAL'],
                'RETER_FACS'  => $registro['RETER_FACS'],
                'RETER_FETHAB'  => $registro['RETER_FETHAB'],
                'SIM_ECF'  => $registro['SIM_ECF'],
                'TOTAL_PRODUTO'  => $registro['TOTAL_PRODUTO'],
                'SSC_UNIDADE_NEGOCIO'  => $registro['SSC_UNIDADE_NEGOCIO'],
                'SSC_SERVICO'  => $registro['SSC_SERVICO'],
                'ANO_FAT_MANUTENCAO'  => $registro['ANO_FAT_MANUTENCAO'],
                'MES_FAT_MANUTENCAO'  => $registro['MES_FAT_MANUTENCAO'],
                'RETER_FUNDERSUL'  => $registro['RETER_FUNDERSUL'],
                'RETER_ROYALTIES'  => $registro['RETER_ROYALTIES'],
                'NF_COMPLEMENTAR'  => $registro['NF_COMPLEMENTAR'],
                'OBSERVACOES_COMPLEMENTO'  => $registro['OBSERVACOES_COMPLEMENTO'],
                'CPF_CNPJ_CUPOM'  => $registro['CPF_CNPJ_CUPOM'],
                'EX_LOCAL_EMBARQUE'  => $registro['EX_LOCAL_EMBARQUE'],
                'EX_LOCAL_EMBARQUE_UF'  => $registro['EX_LOCAL_EMBARQUE_UF'],
                'NF_AJUSTE'  => $registro['NF_AJUSTE'],
                'CHAVE_NFE_ORIGINAL'  => $registro['CHAVE_NFE_ORIGINAL'],
                'TEXTO_NFS_01'  => $registro['TEXTO_NFS_01'],
                'TEXTO_NFS_02'  => $registro['TEXTO_NFS_02'],
                'TEXTO_NFS_03'  => $registro['TEXTO_NFS_03'],
                'SEU_PEDIDO_ITEM'  => $registro['SEU_PEDIDO_ITEM'],
                'PCV_ENTIDADE_BENEFICIARIA'  => $registro['PCV_ENTIDADE_BENEFICIARIA'],
                'SIM_ENDERECO_ENT_BENEFICIARIA'  => $registro['SIM_ENDERECO_ENT_BENEFICIARIA'],
                'OFC_TIPO_ORDEM_SERVICO'  => $registro['OFC_TIPO_ORDEM_SERVICO'],
                'NECESSARIO_APROVACAO'  => $registro['NECESSARIO_APROVACAO'],
                'IMPOSTO_RETIDO'  => $registro['IMPOSTO_RETIDO'],
                'NUMERO_PARCELAS'  => $registro['NUMERO_PARCELAS'],
                'APROVADO'  => $registro['APROVADO'],
                'BASE_RETENCAO'  => $registro['BASE_RETENCAO'],
                'PIS_RETIDO'  => $registro['PIS_RETIDO'],
                'COFINS_RETIDO'  => $registro['COFINS_RETIDO'],
                'CSLL_RETIDO'  => $registro['CSLL_RETIDO'],
                'OBS_RPS'  => $registro['OBS_RPS'],
                'CHAVE_CTE_REFERENCIADA'  => $registro['CHAVE_CTE_REFERENCIADA'],
                'INDICADOR_PRESENCA_COMPRADOR'  => $registro['INDICADOR_PRESENCA_COMPRADOR'],
                'PESO_LIQUIDO_ORIGINAL'  => $registro['PESO_LIQUIDO_ORIGINAL'],
                'PESO_BRUTO_ORIGINAL'  => $registro['PESO_BRUTO_ORIGINAL'],
                'MODELO_ECF_DEV'  => $registro['MODELO_ECF_DEV'],
                'NUMERO_ORDEM_ECF_DEV'  => $registro['NUMERO_ORDEM_ECF_DEV'],
                'NUMERO_CONTADOR_ECF_DEV'  => $registro['NUMERO_CONTADOR_ECF_DEV'],
                'CORREIOS_RAZAO_CLIENTE'  => $registro['CORREIOS_RAZAO_CLIENTE'],
                'CORREIOS_ENDERECO_CLIENTE'  => $registro['CORREIOS_ENDERECO_CLIENTE'],
                'CORREIOS_BAIRRO_CLIENTE'  => $registro['CORREIOS_BAIRRO_CLIENTE'],
                'CORREIOS_MUNICIPIO_CLIENTE'  => $registro['CORREIOS_MUNICIPIO_CLIENTE'],
                'CORREIOS_UF_CLIENTE'  => $registro['CORREIOS_UF_CLIENTE'],
                'CORREIOS_CEP_CLIENTE'  => $registro['CORREIOS_CEP_CLIENTE'],
                'COMPETENCIA'  => $registro['COMPETENCIA'],
                'TALONARIO_ORIGINAL'  => $registro['TALONARIO_ORIGINAL'],
                'BASE_IPI_DEVOLUCAO'  => $registro['BASE_IPI_DEVOLUCAO'],
                'NUMERO_NOTA_EMPENHO'  => $registro['NUMERO_NOTA_EMPENHO'],
                'CONTRATO_COMPRA_EMPENHO'  => $registro['CONTRATO_COMPRA_EMPENHO'],
                'SERVICO_FORA_MUNICIPIO'  => $registro['SERVICO_FORA_MUNICIPIO'],
                'TEXTO_COMPLEMENTAR_NF'  => $registro['TEXTO_COMPLEMENTAR_NF'],
            
            ];
            
        }
    
        return $array;
    }

    public function getFatSolicitacoes()
    {
        $con = Conexao::conection('vendas');
    
        $sql = "Select 
            CAST( 1 AS INT ) as 'FAT_EMPRESA'   , 
            CAST( 1 AS INT ) as 'FAT_LOCAL'   , 
            CAST( ANOME AS VARCHAR(3) ) as 'SIM_ORIGEM'   , 
            CAST( 45 AS DECIMAL ) as 'FAT_SOLICITACAO'   , 
            CAST( 2 AS INT ) as 'FAT_SOLICITACAO_SEQUENCIA'   , 
            CAST( 6 AS INT ) as 'SIM_LOCAL_DESTINO'   , 
            CAST( 5 AS DECIMAL(14) ) as 'PCV_ENTIDADE'   , 
            CAST( 4 AS DECIMAL(14) ) as 'PCV_ENTIDADE_FATURAMENTO'   , 
            CAST( 9 AS INT ) as 'SIM_ENDERECO_FATURAMENTO'   , 
            CAST( 5 AS INT ) as 'SIM_ENDERECO_ENTREGA'   , 
            CAST( 6 AS INT ) as 'SIM_ENDERECO_COBRANCA'   , 
            CAST( 2 AS INT ) as 'SIM_OPERACAO'   , 
            CAST( 1 AS INT ) as 'SIM_VIA_TRANSPORTE'   , 
            CAST( 4 AS DECIMAL(14) ) as 'SIM_DOCUMENTO_ID'   , 
            CAST( ANOME AS VARCHAR(4) ) as 'PCV_PLANO_PAGAMENTO'   , 
            CAST( 5 AS INT ) as 'PCV_TIPO_TAB_PRECO'   , 
            CAST( 1 AS DECIMAL(14) ) as 'PCV_TRANSPORTADORA'   , 
            CAST( ANOME AS VARCHAR(10) ) as 'CGF_CENTRO_CUSTO'   , 
            CAST( 4 AS INT ) as 'FAT_TIPO_SOLICITACAO'   , 
            CAST( 9 AS INT ) as 'TIPO_NOTA_FISCAL'   , 
            CAST( 6 AS INT ) as 'TIPO_FRETE'   , 
            CAST( 3 AS INT ) as 'STATUS'   , 
            CAST( 2 AS DECIMAL ) as 'PEDIDO_ORIGINAL'   , 
            CAST( 4 AS INT ) as 'PEDIDO_SEQ_ORIGINAL'   , 
            CAST( 7 AS DECIMAL ) as 'NF_ORIGINAL'   , 
            CAST( GETDATE() AS DATE ) as 'DATA_EMISSAO_NF_ORIGINAL'   , 
            CAST( GETDATE() AS DATE ) as 'DATA_SOLICITACAO'   , 
            CAST( GETDATE() AS DATE ) as 'DATA_PROVAVEL_FATURAMENTO'   , 
            CAST( GETDATE() AS DATE ) as 'DATA_PRECO'   , 
            CAST( ANOME AS VARCHAR(40) ) as 'SEU_PEDIDO'   , 
            CAST( 1 AS INT ) as 'COMPROMISSO'   , 
            CAST( 6 AS INT ) as 'NF_DIGITADA'   , 
            CAST( 6 AS INT ) as 'EMITE_NF'   , 
            CAST( 9 AS DECIMAL(5,2) ) as 'PERC_FRETE'   , 
            CAST( 8 AS DECIMAL(5,2) ) as 'PERC_SEGURO'   , 
            CAST( 7 AS DECIMAL(5,2) ) as 'PERC_DESCONTO'   , 
            CAST( 4 AS DECIMAL(5,2) ) as 'PERC_DESCONTO_FINANCEIRO'   , 
            CAST( 5 AS DECIMAL(5,2) ) as 'PERC_ENCARGOS_FINANCEIROS'   , 
            CAST( 6 AS INT ) as 'DIAS_DESCONTO_FINANCEIRO'   , 
            CAST( 3 AS DECIMAL(16,2) ) as 'VALOR_ANTECIPADO'   , 
            CAST( 2 AS DECIMAL(16,2) ) as 'VALOR_FRETE'   , 
            CAST( 5 AS DECIMAL(16,2) ) as 'VALOR_SEGURO'   , 
            CAST( 1 AS DECIMAL(16,2) ) as 'VALOR_OUT_DESPESAS'   , 
            CAST( 4 AS DECIMAL(16,2) ) as 'VALOR_DESCONTO'   , 
            CAST( 7 AS DECIMAL(16,2) ) as 'VALOR_ENCARGOS_FINANCEIROS'   , 
            CAST( 8 AS DECIMAL(16,4) ) as 'PESO_LIQUIDO'   , 
            CAST( 9 AS DECIMAL(16,4) ) as 'PESO_BRUTO'   , 
            CAST( ANOME AS VARCHAR(20) ) as 'CFO_ITENS'   , 
            CAST( ANOME AS VARCHAR(140) ) as 'OBSERVACAO_FATURAMENTO_01'   , 
            CAST( ANOME AS VARCHAR(140) ) as 'OBSERVACAO_FATURAMENTO_02'   , 
            CAST( ANOME AS VARCHAR(140) ) as 'OBSERVACAO_FATURAMENTO_03'   , 
            CAST( ANOME AS VARCHAR(256) ) as 'OBSERVACAO_NOTA_FISCAL_01'   , 
            CAST( ANOME AS VARCHAR(256) ) as 'OBSERVACAO_NOTA_FISCAL_02'   , 
            CAST( ANOME AS VARCHAR(256) ) as 'OBSERVACAO_NOTA_FISCAL_03'   , 
            CAST( 8 AS DECIMAL(16,2) ) as 'BASE_ICMS'   , 
            CAST( 4 AS DECIMAL(16,2) ) as 'VALOR_ICMS'   , 
            CAST( 65 AS DECIMAL(16,2) ) as 'BASE_ICMS_SUBST_TRIBUTARIA'   , 
            CAST( 15 AS DECIMAL(16,2) ) as 'VALOR_ICMS_SUBST_TRIBUTARIA'   , 
            CAST( 23 AS DECIMAL(16,2) ) as 'BASE_IPI'   , 
            CAST( 6 AS DECIMAL(16,2) ) as 'VALOR_IPI'   , 
            CAST( 5 AS DECIMAL(16,2) ) as 'VALOR_ISS'   , 
            CAST( 4 AS DECIMAL(16,2) ) as 'BASE_ISS'   , 
            CAST( 1 AS DECIMAL(16,2) ) as 'BASE_IRRF'   , 
            CAST( 2 AS DECIMAL(16,2) ) as 'VALOR_IRRF'   , 
            CAST( ANOME AS VARCHAR(10) ) as 'FCA_LINHA'   , 
            CAST( 5 AS DECIMAL ) as 'FAT_NOTA_FISCAL'   , 
            CAST( 65 AS INT ) as 'FAT_TALONARIO'   , 
            CAST( GETDATE() AS DATE ) as 'DATA_EMISSAO_NF'   , 
            CAST( 1 AS INT ) as 'CLIENTE_EVENTUAL'   , 
            CAST( 5 AS DECIMAL(5,2) ) as 'PERC_ICMS'   , 
            CAST( 6 AS DECIMAL(7,4) ) as 'PERC_REDUCAO_ICMS'   , 
            CAST( 51 AS DECIMAL(5,2) ) as 'PERC_ICMS_FRETE'   , 
            CAST( 62 AS DECIMAL(14) ) as 'SIM_REPRESENTANTE'   , 
            CAST( ANOME AS VARCHAR(15) ) as 'SAC_USUARIO_CADASTRO'   , 
            CAST( ANOME AS VARCHAR(15) ) as 'SAC_USUARIO_CORRECAO'   , 
            CAST( ANOME AS VARCHAR(15) ) as 'SAC_USUARIO_LIBERACAO'   , 
            CAST( 5 AS INT ) as 'NF_DIGITADA_INCONSISTENTE'   , 
            CAST( ANOME AS VARCHAR(6) ) as 'SIM_SEGMENTO'   , 
            CAST( ANOME AS VARCHAR(256) ) as 'OBSERVACAO_NOTA_FISCAL_04'   , 
            CAST( ANOME AS VARCHAR(256) ) as 'OBSERVACAO_NOTA_FISCAL_05'   , 
            CAST( 45 AS DECIMAL(16,2) ) as 'VALOR_IPI_DEVOLUCAO'   , 
            CAST( 9 AS INT ) as 'SIM_BANCO'   , 
            CAST( 6 AS DECIMAL ) as 'SIM_AGENCIA'   , 
            CAST( 3 AS DECIMAL(12) ) as 'SIM_CONTA_CORRENTE'   , 
            CAST( ANOME AS VARCHAR(8) ) as 'PCV_VEICULO'   , 
            CAST( ANOME AS VARCHAR(40) ) as 'NOME_MOTORISTA'   , 
            CAST( 5 AS DECIMAL(14) ) as 'PCV_MOTORISTA'   , 
            CAST( 4 AS INT ) as 'GERA_SERVICO'   , 
            CAST( 1 AS INT ) as 'FAT_LOCAL_SERVICO'   , 
            CAST( 2 AS DECIMAL(5,2) ) as 'PERC_APROVEITAMENTO'   , 
            CAST( 5 AS INT ) as 'BLOQUEADO'   , 
            CAST( 6 AS DECIMAL(5,2) ) as 'PERC_SERVICO_NF'   , 
            CAST( 3 AS INT ) as 'CAR_TIPO_COBRANCA'   , 
            CAST( 9 AS DECIMAL(16,4) ) as 'FRETE_VENDA'   , 
            CAST( ANOME AS VARCHAR(2) ) as 'UF_VEICULO'   , 
            CAST( ANOME AS VARCHAR(11) ) as 'RG_MOTORISTA'   , 
            CAST( 6 AS INT ) as 'PCV_TIPO_CLIENTE'   , 
            CAST( 2 AS DECIMAL(16,2) ) as 'VALOR_JUROS'   , 
            CAST( GETDATE() AS DATE ) as 'DATA_SAIDA'   , 
            CAST( 5 AS DECIMAL(16,2) ) as 'BASE_PIS_RETIDO'   , 
            CAST( 4 AS DECIMAL(16,2) ) as 'VALOR_PIS_RETIDO'   , 
            CAST( 1 AS DECIMAL(16,2) ) as 'BASE_COFINS_RETIDO'   , 
            CAST( 2 AS DECIMAL(16,2) ) as 'VALOR_COFINS_RETIDO'   , 
            CAST( 3 AS DECIMAL(16,2) ) as 'BASE_CSLL_RETIDO'   , 
            CAST( 6 AS DECIMAL(16,2) ) as 'VALOR_CSLL_RETIDO'   , 
            CAST( 9 AS INT ) as 'VENDA_VISTA_CHEQUE'   , 
            CAST( 8 AS DECIMAL(16,2) ) as 'VALOR_ADIANTAMENTO'   , 
            CAST( ANOME AS VARCHAR(40) ) as 'NOME_USUARIO'   , 
            CAST( 4 AS INT ) as 'QTD_DIAS_PRORROGAR_NF'   , 
            CAST( 2 AS DECIMAL(14) ) as 'CMO_AGRUPAMENTO_ID'   , 
            CAST( GETDATE() AS DATE ) as 'CREATED'   , 
            CAST( GETDATE() AS DATE ) as 'UPDATED'   , 
            CAST( 1 AS INT ) as 'RETER_FUNRURAL'   , 
            CAST( 4 AS INT ) as 'RETER_FACS'   , 
            CAST( 2 AS INT ) as 'RETER_FETHAB'   , 
            CAST( ANOME AS VARCHAR(20) ) as 'SIM_ECF'   , 
            CAST( 3 AS DECIMAL(16,2) ) as 'TOTAL_PRODUTO'   , 
            CAST( 6 AS INT ) as 'SSC_UNIDADE_NEGOCIO'   , 
            CAST( ANOME AS VARCHAR(1) ) as 'SSC_SERVICO'   , 
            CAST( 1 AS INT ) as 'ANO_FAT_MANUTENCAO'   , 
            CAST( 4 AS INT ) as 'MES_FAT_MANUTENCAO'   , 
            CAST( 2 AS INT ) as 'RETER_FUNDERSUL'   , 
            CAST( 3 AS INT ) as 'RETER_ROYALTIES'   , 
            CAST( 6 AS INT ) as 'NF_COMPLEMENTAR'   , 
            CAST( ANOME AS VARCHAR(2000) ) as 'OBSERVACOES_COMPLEMENTO'   , 
            CAST( ANOME AS VARCHAR(20) ) as 'CPF_CNPJ_CUPOM'   , 
            CAST( ANOME AS VARCHAR(60) ) as 'EX_LOCAL_EMBARQUE'   , 
            CAST( ANOME AS VARCHAR(2) ) as 'EX_LOCAL_EMBARQUE_UF'   , 
            CAST( 9 AS INT ) as 'NF_AJUSTE'   , 
            CAST( ANOME AS VARCHAR(44) ) as 'CHAVE_NFE_ORIGINAL'   , 
            CAST( ANOME AS VARCHAR(140) ) as 'TEXTO_NFS_01'   , 
            CAST( ANOME AS VARCHAR(140) ) as 'TEXTO_NFS_02'   , 
            CAST( ANOME AS VARCHAR(140) ) as 'TEXTO_NFS_03'   , 
            CAST( 6 AS INT ) as 'SEU_PEDIDO_ITEM'   , 
            CAST( 45 AS DECIMAL(14) ) as 'PCV_ENTIDADE_BENEFICIARIA'   , 
            CAST( 4 AS INT ) as 'SIM_ENDERECO_ENT_BENEFICIARIA'   , 
            CAST( ANOME AS VARCHAR(4) ) as 'OFC_TIPO_ORDEM_SERVICO'   , 
            CAST( 6 AS INT ) as 'NECESSARIO_APROVACAO'   , 
            CAST( 5 AS DECIMAL(16,2) ) as 'IMPOSTO_RETIDO'   , 
            CAST( 4 AS INT ) as 'NUMERO_PARCELAS'   , 
            CAST( 2 AS INT ) as 'APROVADO'   , 
            CAST( 3 AS DECIMAL(16,2) ) as 'BASE_RETENCAO'   , 
            CAST( 6 AS DECIMAL(16,2) ) as 'PIS_RETIDO'   , 
            CAST( 9 AS DECIMAL(16,2) ) as 'COFINS_RETIDO'   , 
            CAST( 8 AS DECIMAL(16,2) ) as 'CSLL_RETIDO'   , 
            CAST( ANOME AS VARCHAR(1024) ) as 'OBS_RPS'   , 
            CAST( ANOME AS VARCHAR(44) ) as 'CHAVE_CTE_REFERENCIADA'   , 
            CAST( 4 AS INT ) as 'INDICADOR_PRESENCA_COMPRADOR'   , 
            CAST( 5 AS DECIMAL(16,4) ) as 'PESO_LIQUIDO_ORIGINAL'   , 
            CAST( 6 AS DECIMAL(16,4) ) as 'PESO_BRUTO_ORIGINAL'   , 
            CAST( ANOME AS VARCHAR(2) ) as 'MODELO_ECF_DEV'   , 
            CAST( 2 AS INT ) as 'NUMERO_ORDEM_ECF_DEV'   , 
            CAST( 1 AS INT ) as 'NUMERO_CONTADOR_ECF_DEV'   , 
            CAST( ANOME AS VARCHAR(100) ) as 'CORREIOS_RAZAO_CLIENTE'   , 
            CAST( ANOME AS VARCHAR(100) ) as 'CORREIOS_ENDERECO_CLIENTE'   , 
            CAST( ANOME AS VARCHAR(30) ) as 'CORREIOS_BAIRRO_CLIENTE'   , 
            CAST( ANOME AS VARCHAR(30) ) as 'CORREIOS_MUNICIPIO_CLIENTE'   , 
            CAST( ANOME AS CHAR(2) ) as 'CORREIOS_UF_CLIENTE'   , 
            CAST( 4 AS DECIMAL ) as 'CORREIOS_CEP_CLIENTE'   , 
            CAST( GETDATE() AS DATE ) as 'COMPETENCIA'   , 
            CAST( 6 AS INT ) as 'TALONARIO_ORIGINAL'   , 
            CAST( 9 AS DECIMAL(16,2) ) as 'BASE_IPI_DEVOLUCAO'   , 
            CAST( ANOME AS VARCHAR(22) ) as 'NUMERO_NOTA_EMPENHO'   , 
            CAST( ANOME AS VARCHAR(60) ) as 'CONTRATO_COMPRA_EMPENHO'   , 
            CAST( 4 AS INT ) as 'SERVICO_FORA_MUNICIPIO'   , 
            CAST( ANOME AS VARCHAR(500) ) as 'TEXTO_COMPLEMENTAR_NF'   
        
        FROM  FS_NEW.FSMASTER.ARQ01 WHERE     ACODI = 350
        ";

        $query = sqlsrv_query($con,$sql);

        $array = FatSolicitacoes::getArray($query);

        $json = json_encode(['FatSolicitacoes' => $array]);

        echo $json;
    }

    public function findFatSolicitacoes($parametro)
    {
        $con = Conexao::conection();

        $sql = "aqui vai um select com where";

        $query = sqlsrv_query($con, $sql);

        $array = FatSolicitacoes::getArray($query);

        $json = json_encode(['PcvPedidoItens' => $array]);

        echo $json;
        
    }
}

if(!empty($_GET['parametro'])){
    $parametro = $_GET['parametro'];

    FatSolicitacoes::findFatSolicitacoes($parametro);
}else{

    
    FatSolicitacoes::getFatSolicitacoes();
}

?>